/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculatorsIndexRouteImport } from './routes/calculators.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as CalculatorsSlugRouteImport } from './routes/calculators.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsIndexRoute = CalculatorsIndexRouteImport.update({
  id: '/calculators/',
  path: '/calculators/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsSlugRoute = CalculatorsSlugRouteImport.update({
  id: '/calculators/$slug',
  path: '/calculators/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculators/$slug': typeof CalculatorsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/calculators/': typeof CalculatorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculators/$slug': typeof CalculatorsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/calculators': typeof CalculatorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculators/$slug': typeof CalculatorsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/calculators/': typeof CalculatorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calculators/$slug' | '/blog/' | '/calculators/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calculators/$slug' | '/blog' | '/calculators'
  id: '__root__' | '/' | '/calculators/$slug' | '/blog/' | '/calculators/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorsSlugRoute: typeof CalculatorsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CalculatorsIndexRoute: typeof CalculatorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/': {
      id: '/calculators/'
      path: '/calculators'
      fullPath: '/calculators/'
      preLoaderRoute: typeof CalculatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/$slug': {
      id: '/calculators/$slug'
      path: '/calculators/$slug'
      fullPath: '/calculators/$slug'
      preLoaderRoute: typeof CalculatorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorsSlugRoute: CalculatorsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CalculatorsIndexRoute: CalculatorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
